spring:
  application:
    name: creatorStore

  # Database Information
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}

  #ORM hibernate configuration

  jpa:
    database-platform:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

